name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      BOOK_DIR    : droneDOCS
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@v1.2.4
      with:                                  
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: main
#     - name: GitHub MD Book
#       uses: gryphonshafer/GitHub-MD-Book@v3

#     - name: Build and Deploy 🚀
#       uses: onejar99/gitbook-build-publish-action@v1.0.2
